spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ceapp
    username: root
    password: roM72t+45
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.xml
    drop-first: false
    database-change-log-table: USER_MS_DBCHANGELOG
    database-change-log-lock-table:  USER_MS_DBCHANGELOGLOCK
  server:
    port: 8080
    servlet:
      context-path: /users-ms